;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        eval-last-sexp
        eval-sexp-and-replace
        haskell-mode-contextual-space
        kill-sexp
        paredit-backward
        paredit-delete-region
        paredit-forward-kill-word
        paredit-forward-up
        paredit-kill
        paredit-wrap-round
        repeat
        smarter-move-beginning-of-line
        sp-forward-slurp-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        kill-region
        paredit-forward-delete
        ))
